eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  application:
    name: springcloud-zuul
server:
  port: 8081
zuul:
  routes:
    springcloud-api: /openapi/**
  ignored-patterns:
    - /springcloud-api/api/get
